### ISSUE TITLE
Owin window changes through operations

### ISSUE THREAD

**Issue by spono** [spatstat/spatstat.geom#10]
I have a set of georeferenced points and I would like to describe their local spatial distribution pattern using the Clark-Evans index.

I'm willing to rasterise the results bu I didn't find any "direct" solution. Hence I tried to convert pixels to polygons [`poly` object, a SpatVector from `terra` package] and use them in a loop as a window for `spatstat.core::clarkevans(spatstat.geom::ppp(data$X,data$Y, win=as.owin(ext(poly[1])@ptr$vector)))` but points are dropped because they're considered outside the window:

```
> spatstat.geom::ppp(data$X,data$Y, win=as.owin(ext(poly[1])@ptr$vector))

Planar point pattern: 0 points
window: rectangle = [0, 1] x [0, 1] units
*** 3628312 illegal points stored in attr(,“rejects”) ***
Warning message:
3628312 points were rejected as lying outside the specified window 
```

I checked the window alone and I get what looks like a correct one (correct CRS and pixel dimension, i.e. 1x1m):

```
> windb = as.owin(ext(rp[cp])@ptr$vector)
> windb
window: rectangle = [740703, 740704] x [5166180, 5166181] units
```

but when I create a `ppp` object the window shows a different extent:
```
> mypoints = spatstat.geom::ppp(data$X,data$Y, win=as.owin(ext(poly[1])@ptr$vector))

> str( mypoints )
List of 5
 $ window    :List of 4
  ..$ type  : chr "rectangle"
  ..$ xrange: num [1:2] 0 1
  ..$ yrange: num [1:2] 0 1
  ..$ units :List of 3
  .. ..$ singular  : chr "unit"
  .. ..$ plural    : chr "units"
  .. ..$ multiplier: num 1
  .. ..- attr(*, "class")= chr "unitname"
  ..- attr(*, "class")= chr "owin"
 $ n         : int 0
 $ x         : num(0) 
 $ y         : num(0) 
 $ markformat: chr "none"
 - attr(*, "class")= chr "ppp"
 - attr(*, "rejects")=List of 5
  ..$ window    :List of 5
  .. ..$ type  : chr "polygonal"
  .. ..$ xrange: num [1:2] 0 740782
  .. ..$ yrange: num [1:2] 0 5166181
  .. ..$ bdry  :List of 1
  .. .. ..$ :List of 2
  .. .. .. ..$ x: num [1:84] 740778 740777 740777 740776 740773 ...
  .. .. .. ..$ y: num [1:84] 5166156 5166159 5166160 5166163 5166172 ...
  .. ..$ units :List of 3
  .. .. ..$ singular  : chr "unit"
  .. .. ..$ plural    : chr "units"
  .. .. ..$ multiplier: num 1
  .. .. ..- attr(*, "class")= chr "unitname"
  .. ..- attr(*, "class")= chr "owin"
  ..$ n         : int 3628312
  ..$ x         : num [1:3628312] 740721 740721 740721 740721 740721 ...
  ..$ y         : num [1:3628312] 5166181 5166181 5166181 5166181 5166181 ...
  ..$ markformat: chr "none"
  ..- attr(*, "class")= chr "ppp"



```

**Comment by baddstats** [comment]
The argument of `ppp` specifying the window should be named `window`, not `win`.

 (The name must be matched exactly because the formal argument `win` is listed after  `...` in the arguments of `ppp`.)

Any of the following should work:

    spatstat.geom::ppp(data$X,data$Y, window=as.owin(ext(poly[1])@ptr$vector))
    spatstat.geom::ppp(data$X,data$Y, window=owin(poly=ext(poly[1])@ptr$vector))
    spatstat.geom::ppp(data$X,data$Y, poly=ext(poly[1])@ptr$vector)

**Comment by spono** [comment]
Gosh...I can't believe it was matter of an oversight...sorry for wasting your time and thanks for the availability
