### ISSUE TITLE
Bug in new code in `crosspairs.ppp()`

### ISSUE THREAD

**Issue by rubak** [spatstat/spatstat.geom#11]
Reproducible example here:

https://stackoverflow.com/q/72616066/3341769

The underlying issue is that the number of points `nX` and `nY` both are `integer` and when they are sufficiently large the product `nXY = nX*nY` overflows:

```
> 8000L*1000000L
[1] NA
Warning message:
In 8000L * 1000000L : NAs produced by integer overflow
```

This did not happen with the old version of the code that overestimated the number of pairs in another way.

We could simply coerce to `double` when calculating the product: `nXY = as.double(nX) * as.double(nY)`

Afterwards this overestimate is improved and checked against `.Machine$integer.max` so I don't see any problem with `nXY` being a double, but I may be missing something.

**Comment by baddstats** [comment]
Thanks!
I agree. Will fix asap

**Comment by baddstats** [comment]
Fixed in `spatstat.geom 2.4-0.029`
