### ISSUE TITLE
`as.data.frame` doesn't work when `nsim > 1`

### ISSUE THREAD

**Issue by CGMossa** [spatstat/spatstat.geom#12]
When using `rpoispp` I've discovered that `as.data.frame` doesn't work with `nsim > 1`. As

```r
> rpoispp(100, nsim = 12) |>
+   as.data.frame()
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 85, 94, 106, 100, 91, 111, 97, 98, 89, 92
```

I can get around this, but honestly I think there should be a `as.data.frame.ppplist`:

```r
as.data.frame.ppplist <- function(x, ...) {
  do.call(what = rbind,
          args = lapply(x, as.data.frame.ppp, ...))
}
```

Unfortunately, this doesn't get us all the way, as:

```r
> rpoispp(2, nsim = 12) |>
+   as.data.frame()
                        x          y
Simulation 1.1  0.3500342 0.45925195
Simulation 1.2  0.7359299 0.17781784
Simulation 1.3  0.9254328 0.51028685
Simulation 1.4  0.6157233 0.86186033
Simulation 1.5  0.7507317 0.81154081
Simulation 2.1  0.7558588 0.85644016
Simulation 2.2  0.2260337 0.27851179
Simulation 5    0.7813405 0.42246301
Simulation 8    0.5706969 0.86216191
Simulation 9.1  0.1003703 0.62929461
Simulation 9.2  0.3968383 0.08644775
Simulation 10.1 0.7720783 0.32627933
Simulation 10.2 0.6414470 0.99893650
Simulation 11   0.1248797 0.88483252
```

After the `.` the index of each point in the simulation set is given only if the simulation yielded more than 1 point...

**Comment by rolfTurner** [comment]
It would appear that you want, e.g., the row label "Simulation 5"
to be "Simulation 5.1".  This seems to me to be a characteristic of
the base function rbind.().  It is not really a spatstat issue, IMHO.

One could do some sort of shaganappi work-around.  E.g.:

set.seed(42)
X <- rpoispp(2,nsim=12)
Y <- do.call(rbisnd,lapply(X,as.data.frame))
nms <- lapply(1:length(X),function(k,x,r){rep(x[k],r[k])},
              x=names(X),r=sapply(X,npoints))
tgs <- unlist(lapply(nms,function(x){seq_len(length.out=length(x))}))
newnms <- paste(unlist(nms),tgs,sep=".")
YY <- Y
rownames(YY) <- newnms

You will observe that Y has rownames like unto
Simulation 6 
Simulation 7 
whereas in YY these are replaced by
Simulation 6.1 
Simulation 7.1 
which I presume is what you want.

Such a workaround could be included in your proposed
as.data.frame.ppplist() method.

But to my mind le jeu n'en vaut pas la chandelle.

**Comment by baddstats** [comment]
`as.data.frame` is generic. When you say it "doesn't work", you mean that there is no method for objects of class `ppplist`, and that you expected there to be one, and were surprised to get an error (the call is dispatched to the method `as.data.frame.list` in base R which leads to an error). So you would like there to be a method `as.data.frame.ppplist`. 

But you also say that you know how to work around this. 

As @rolfTurner says, the package authors have to make a judgement whether this is worth the effort (and we are under pressure from CRAN to keep the package as small as possible). This judgement depends on how many people and 'use cases' are likely to need this code.

The method could be something like

    as.data.frame.ppplist <- function(x, ...) {
        y <- lapply(x, as.data.frame)
        z <- lapply(y, function(a) { if(nrow(a) > 0) { row.names(a) <- paste("Point", seq_len(nrow(a))}; a })
        do.call(rbind, z)
    }

I think this is small enough to add to `spatstat.geom`. It will be done shortly (in `spatstat.geom 2.999-999.004`)

**Comment by baddstats** [comment]
Done.
