### ISSUE TITLE
quadratcount issue with irregular window

### ISSUE THREAD

**Issue by mgimond** [spatstat/spatstat.geom#16]
As of `spatstat.geom` version `3.2-2`, `quadratcount` will output count values in the wrong order if one or more cells do not cover an irregular window. For example, the following works as expected:

```r
library(spatstat)
Q <- quadratcount(humberside, 2, 3)
plot(humberside, pch = 3)
plot(Q, add=TRUE, col="blue", cex=1.5, lwd=2)
```
<img width="406" alt="good_output" src="https://github.com/spatstat/spatstat.geom/assets/7494709/ae68fe40-830f-4a4b-b3cf-395219f1644f">

However, if one applies a grid that has cells not covered by the irregular window, we get:

```r
Q <- quadratcount(humberside, 5, 3)
plot(humberside, pch = 3)
plot(Q, add=TRUE, col="blue", cex=1.5, lwd=2)
```

<img width="464" alt="bad_output" src="https://github.com/spatstat/spatstat.geom/assets/7494709/39c7dc27-6437-4856-92cf-42d447f4eb74">

This is a result of `Q` outputting the counts in the wrong order

```r
Q
```

```
tile
Tile row 1, col 1 Tile row 1, col 2 Tile row 1, col 3 Tile row 1, col 4 Tile row 2, col 1 Tile row 2, col 2 
                0                 3                 0                 2                 2                 3 
Tile row 2, col 3 Tile row 2, col 4 Tile row 2, col 5 Tile row 3, col 2 Tile row 3, col 3 Tile row 3, col 4 
               14               117                19                 5                35                 0 
Tile row 3, col 5 
                3 
```

This issue does not manifest itself with `spatsat.geom` `3.0-3` which outputs the values in the correct order shown here:
```
tile
Tile row 1, col 1 Tile row 1, col 2 Tile row 1, col 3 Tile row 1, col 4 Tile row 2, col 1 Tile row 2, col 2 
                0                 0                 3                19                 3                 2
Tile row 2, col 3 Tile row 2, col 4 Tile row 2, col 5 Tile row 3, col 2 Tile row 3, col 3 Tile row 3, col 4 
               14                 5                 0                 2               117                35 
Tile row 3, col 5 
                3 
```

**Comment by baddstats** [comment]
Thank you for drawing this to our attention.
I think it is now fixed in the development version `spatstat.geom 3.2-2.003`. 
Please let us know if you see any further problems.

**Comment by mgimond** [comment]
That works. Thanks for the quick turnaround!

**Comment by baddstats** [comment]
There were some remaining problems with the `quadratcount` code that affected the results of `quadrat.test`.
I think/hope these are now all fixed in `spatstat.geom 3.2-2.006`. 

This fix required further edits to `quadratcount` and `intensity.quadratcount` so you may want to check again that everything still works for you.

We have included your two examples in the package test code so they will never be wrong again!

**Comment by baddstats** [comment]
Fixed in public release `spatstat.geom 3.2-4`
