### ISSUE TITLE
quadratcount issue

### ISSUE THREAD

**Issue by Jadamso** [spatstat/spatstat.geom#17]
First, thanks for the great package. There appears to be an error when passing tesselation data to `quadratcount`

E.g., the following code yields "Error: object 'Xcount' not found"

```
library(spatstat)
## Regular Point Grid
tess_y <-  tess_x <- seq(0,1,length.out=6)
tess_im <- tess(xgrid=tess_x, ygrid=tess_y)

## Counts of Point Process
X  <- rpoint(12, function(x,y) { (x^2 + y^2)^2} )
Nx <- quadratcount(X, tess=tess_im)
```

**Comment by rubak** [comment]
Thanks for letting us know @Jadamso. I can confirm that it is a bug, and we will fix it soon.

@baddstats do you already have the fast code for the rectangular case mentioned in the comment in line 60 of `quadratcount.R` or should we write it?

https://github.com/spatstat/spatstat.geom/blob/bfb12fe923815c26e4a44e8784ba83cb12470d2d/R/quadratcount.R#L59-L61

 A very quick fix is to omit it and just use the else clause which does the job just fine.
