### ISSUE TITLE
spatstat.sparse dependency

### ISSUE THREAD

**Issue by bastistician** [spatstat/spatstat.geom#3]
Thank you for providing the "owin" functionality as a separate package. I think this move makes a lot of sense.

I just stumbled on the following minor detail of the new spatstat structure: why would the new **spatstat.geom** need to import functionality for sparse 3D arrays? I've checked which functions from **spatstat.sparse** are currently used by **spatstat.geom**:

1. `spatstat.sparse::RelevantNA()` is used only once in `as.im.data.frame()`
2. `spatstat.sparse::grokIndexVector()` is used only once in `ppsubset()`

In the first case, `RelevantNA(zk)` could simply be replaced by `vector(typeof(zk))[1L]`.
To resolve the second dependency, maybe the function `grokIndexVector()` could be moved to **spatstat.utils**, which both **spatstat.sparse** and **spatstat.geom** import anyway? `grokIndexVector()` itself only needs `sortunique()`, which is part of **spatstat.utils**.
After these changes, **spatstat.geom** would no longer need to depend on **spatstat.sparse** (with additional recursive dependencies **abind** and **tensor**).

**Comment by baddstats** [comment]
Thank you for pointing this out. We will give it some thought. CRAN would certainly approve.

The main problem is related to future development. We plan to add new features to **spatstat.geom** which depend on **spatstat.sparse** (code already exists). Also the indexing code such as `grokIndexVector` is heavily used in **spatstat.sparse**, so if we do as you suggest, then it will be more complicated to make changes. 

However we will give this further consideration.

**Comment by baddstats** [comment]
OK, this has been implemented in the latest versions of the packages **spatstat.utils**, **spatstat.sparse** and **spatstat.geom** available on GitHub.

**Comment by bastistician** [comment]
Thank you for considering my suggestion!

Sorry, I didn't know that **spatstat.sparse** will have more to offer for **spatstat.geom** in the future. In that case, it might make sense to import **spatstat.sparse**; it isn't that heavy overall. Or maybe such additional functionality could then be made optional (as a *suggested* package). Anyway, I hope my suggestion won't disturb spatstat development! Thank you for your continuous efforts!
