### ISSUE TITLE
Can't install spatstat.geom on Windows 10 (R version: 4.1.2)

### ISSUE THREAD

**Issue by JorgeVindelAlfageme** [spatstat/spatstat.geom#7]
Hi:
I'm trying to install Seurat and one of the necessary packages to do so is spatstat.geom. When I try to install it, I get this error message:
> No se esperaba "zareadiff.o auctionbf.o bdrymask.o close3pair.o closepair.o connect.o dinfty.o discarea.o discs.o dist2dpath.o distan3.o distances.o distmapbin.o dwpure.o exactPdist.o exactdist.o fardist.o hasclose.o hotrod.o init.o knndistance.o knngrid.o loccum.o metricPdist.o minnnd.o nearestpix.o nn3Ddist.o nnMDdist.o nndistance.o nngrid.o periodic.o poly2im.o quasirandom.o raster.o rasterfilter.o scan.o seg2pix.o tabnum.o trigraf.o uniquemap.o veegraf.o whist.o xyseg.o" en este momento.
make: *** [spatstat.geom.dll] Error 255
ERROR: compilation failed for package 'spatstat.geom'
\* removing 'C:/Users/jvalf/Documents/R/win-library/4.1/spatstat.geom'
Warning in install.packages :
 > installation of package ‘spatstat.geom’ had non-zero exit status

Have you ever encountered this problem and know how to solve it? Thanks in advance.

**Comment by rubak** [comment]
No, I haven't seen this before. Does it also happen with previous versions of `spatstat.geom`? Can you install other packages from source (e.g. `install.packages("Rcpp", type = "source")`)?

Can you install the binary version from r-universe.org?

```r
install.packages('spatstat.geom', repos = "https://spatstat.r-universe.dev", )
```

If you don't need the newest version, which was just released and only exists as source version you can install the previous binary version from CRAN:

```r
install.packages('spatstat.geom', type = "binary")
```

**Comment by JorgeVindelAlfageme** [comment]
Hello, again:
Thank you, @rubak for your quick response. The last thing I tried was to install it using the command: `devtools::install_github("spatstat/spatstat.geom")`. It seems that it worked, but if I find further issues related to this topic, I'll make sure I'll use the commands you posted to reinstall the package and try again.
For now, I'll close the topic.
Regards.
