### ISSUE TITLE
nncross returns Inf when k>1 and when k is integer vector

### ISSUE THREAD

**Issue by tshearm** [spatstat/spatstat.geom#9]
The example code for third-nearest neighbor reproduces the error but on my code it strangely works for some points but not for others. It returns the correct "which" points. 

#First to third nearest neighbours return Inf
 NXY <- nncross(X, Y, k=1:3)
 NXY[1:3,]
  dist.1 dist.2 dist.3 which.1 which.2 which.3
1    Inf    Inf    Inf       7       1       4
2    Inf    Inf    Inf      14       3       9
3    Inf    Inf    Inf       7      17      19
 #Using k=1 returns the correct distances
 NXY <- nncross(X, Y, k=1)
 NXY[1:3,]
        dist which
1 0.08885846     7
2 0.01831034    14
3 0.13885983     7

**Comment by rubak** [comment]
@tshearm  why did you close this issue without further comments? Is it no longer relevant?

**Comment by baddstats** [comment]
This is a bug. Thank you for drawing it to our attention.
It will be fixed shortly.

**Comment by tshearm** [comment]
Sorry, I closed it when I realized I wasn't working with the development build. I have tried it now on   the dev build and it is still returning Inf. I figured out a work around by calculating the distance between the points returned. I still don't know why it works with some points and not others.

**Comment by baddstats** [comment]
Fixed in `spatstat.geom 2.3-2.007`

**Comment by tshearm** [comment]
This works now, thanks!
